version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./app:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    image: php:7.4-fpm
    volumes:
      - ./app:/var/www/html
      - php_data:/var/www/html/data
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - mysql_data:/var/lib/mysql

volumes:
  php_data:
  mysql_data:
